# Generated by Django 2.2.8 on 2020-01-05 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 5, 10, 15, 49, 319155, tzinfo=utc), null=True),
        ),
    ]
