# Generated by Django 2.2.8 on 2020-01-05 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0002_auto_20200105_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
